"$schema" = 'https://starship.rs/config-schema.json'


format = '\[$sudo$username@$hostname:$directory\] $character'
right_format = '$package$docker_context$golang$git_branch$git_commit$git_state$git_metrics$git_status$time$cmd_duration'
scan_timeout = 30
command_timeout = 500
add_newline = true
follow_symlinks = true

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ—](bold red)'
vimcmd_symbol = '[â®](bold green)'
vimcmd_replace_symbol = '[â®](bold purple)'
vimcmd_replace_one_symbol = '[â®](bold purple)'
vimcmd_visual_symbol = '[â®](bold yellow)'

[cmd_duration]
min_time = 500
show_milliseconds = false
format = '[$duration]($style)'
style = 'bold yellow'
show_notifications = false
min_time_to_notify = 45_000
notification_timeout = 100_000

[container]
symbol = 'ïˆŸ'
style = 'bold blue dimmed'
disabled = false
format = '[$symbol\$name\]]($style)'

[directory]
truncation_length = 110
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'bold cyan'
disabled = false
read_only = ' ğŸ”’'
read_only_style = 'red'
truncation_symbol = '.../'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
home_symbol = '~'
use_os_path_sep = true

[docker_context]
format = '[$symbol$context]($style) '
symbol = 'ğŸ³ '
only_with_files = true
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
style = 'blue bold'
disabled = false

[gcloud]
format = '[$symbol$account(@$domain)\($project\)(\($region\))|$active|]($style)'
symbol =  'ï¸ó±‡¶ '
style = 'bold blue'
disabled = false

[git_branch]
always_show_remote = true 
format = '[$symbol\[$branch\] ($remote_name:$remote_branch)]($style)'
symbol = 'î‚ '
style = 'bold purple'
only_attached = false
disabled = false

[git_commit]
commit_hash_length = 7
format = '[\(<$hash>$tag\) ]($style)'
style = 	'bold green'
only_detached = false
tag_disabled = false
tag_max_candidates = 0
tag_symbol = ' ï€« '
disabled = false 

[git_state]
rebase = 'REBASE'
merge = 'MERGE'
revert = 'REVERT'
cherry_pick = 'CHERRY-PICK'
bisect = 'BISECT'
am = 'AM'
am_or_rebase = 'AM/RE'
format =	'\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[git_metrics]
added_style = 'bold green'
deleted_style = 'bold red'
only_nonzero_diffs = true
format = '([+$added]($added_style) )([$deleted]($deleted_style) )'
disabled = false
ignore_submodules = true

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '='
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
up_to_date = ''
untracked = '?'
stashed = '$'
modified = '!'
staged = '+'
renamed = 'Â»'
deleted = 'âœ˜'
typechanged = ""
style = 'bold red'
ignore_submodules = true
disabled = false

[golang]
format = '[\[$symbol($version)($mod_version)\]]($style)'
version_format = 'v${raw}'
symbol = 'î˜§ '
detect_extensions = ['go']
detect_files = ['go.mod', 'go.sum', 'go.work', 'glide.yaml', 'Gopkg.yml', 'Gopkg.lock', '.go-version']
detect_folders = ['Godeps']
style = 'bold cyan'
not_capable_style = 'bold red'
disabled = false

[hostname]
ssh_only = false
trim_at = ''
style = 'bold dimmed green'
format = '[$ssh_symbol$hostname]($style)'

[line_break]
disabled = false

[localip]
ssh_only = true
format = '[$localipv4]($style) '
style = 'bold yellow'
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = 'î¿… '
format = '$symbol[${ram}(|${swap})]($style) '
style = 'bold dimmed green'

[os]
format = 	'[$symbol]($style)'
style = 'bold white'
disabled = false

[os.symbols]
AIX = "â¿ "
Alpaquita = "ğŸ”” "
AlmaLinux = "ğŸ’  "
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Android = "ğŸ¤– "
Arch = "ğŸ—ï¸ "
Artix = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ğŸš€ "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Garuda = "ğŸ¦… "
Gentoo = "ğŸ—œï¸ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ğŸ¦ "
Kali = "ğŸ‰ "
Linux = "ğŸ§ "
Mabox = "ğŸ“¦ "
Macos = "ğŸ "
Manjaro = "ğŸ¥­ "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ğŸŒ¿ "
NetBSD = "ğŸš© "
NixOS = "â„ï¸ "
OpenBSD = "ğŸ¡ "
OpenCloudOS = "â˜ï¸ "
openEuler = "ğŸ¦‰ "
openSUSE = "ğŸ¦ "
OracleLinux = "ğŸ¦´ "
Pop = "ğŸ­ "
Raspbian = "ğŸ“ "
Redhat = "ğŸ© "
RedHatEnterprise = "ğŸ© "
RockyLinux = "ğŸ’  "
Redox = "ğŸ§ª "
Solus = "â›µ "
SUSE = "ğŸ¦ "
Ubuntu = "ğŸ¯ "
Ultramarine = "ğŸ”· "
Unknown = "â“ "
Void = "îŠ™  "
Windows = "ğŸªŸ "

[package]
format = '[$symbol$version]($style) '
symbol = 'ó°– '
version_format = 'v${raw}'
style = 'bold blue'
display_private = true
disabled = false

[sudo]
format = '[$symbol]($style)'
style = 'bold blue'
symbol = 'ï€… '
disabled = false

[time]
disabled = false
format = '[\[$time\]]($style) '
style = 'bold yellow'
time_format = '%T'
use_12hr = false
utc_time_offset = '-6'
time_range = '-'

[username]
style_root = 'bold red'
style_user = 	'bold yellow'
format = '[$user]($style)'
show_always = true
disabled = false
